### ISSUE TITLE
Use ForkJoin pervasively for parallelism

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#573]
I would like to redo LensKit's parallelism to use fork/join pervasively, with a single pool parallelizing evaluation tasks, model builds, and evaluations themselves.

The fork/join pool would be injected into the model build processes, so parallelizable components can depend on it directly.

This will be the basis for #564.

We could have different thread counts, too: one for the overall parallelism value, and another for how many evaluators can be run simultaneously.

This is going to involve several subtasks:
- [x] Require data sources to be thread-safe, or provide ways of testing thread safety (#464)
- [ ] Expose fork-join executor (#723)
- [ ] Support parallel item-item builds (#724)
- [x] Parallelize evaluation of test users (#564)
- [ ] Improve evaluator component building parallelism (#726)
