### ISSUE TITLE
Redo data structures

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#730]
We want to redo our data structures to get rid of `SparseVector` and have a better strategy for data access.

- [x] Decide on HPPC, fastutil, or gs-collections (#620)
- [x] Implement new result API (#727)
- [x] Implement sorted array data structures (#729)

**Comment by mdekstrand** [comment]
We will stay with Fastutil for the time being.
