### ISSUE TITLE
Make generalized key-value interfaces for data

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#845]
As per the discussion in the mailing list, we want to have a new key-value conception of data in LensKit.

### Work to Do

- [x] Entity interface (#917)
- [x] DAO interface (#914)
- [x] File-based DAOs (#914)
- [x] Implement specialized entity types (#923)
- [x] Implement bridge DAOs (#925)
- [x] Support crossfolding new DAOs (#929)
- [x] Use new DAOs in evaluator (#930)
- [x] Use new DAOs in command-line tools (#925)
- [x] Support preference domains in new DAOs (#931)

### Background

The idea of the event setup:

- Event is an interface that exposes a key-value interface, with unboxed calls for keys storing longs or doubles (I don’t think we need to worry about other unboxed primitives), and designated getters for fetching user ID, item ID, and timestamp.
- Rating implements Event, and exposes its rating under the ‘rating’ key.
- There’s a general event implementation backed by a hashtable.
- Additional data sources can provide their own implementations as appropriate.
- We may or may not have event IDs.
- Either vector DAOs or summarizing components are available to translate to vectors in item-space (or latent-feature-space, or whatever)

And how we can do DAOs:

> It seems that we need just a few concepts:
>
> - Object types. Most data stores will have user, item, and some kind of event such as ‘rating’.
> - Object IDs. IDs are namespaced per-type, so it is allowed for there to exist a user and item with the same ID as far as LensKit is concerned (However, LensKit never creates objects, so it is fine for the underlying data store to require and/or force all IDs to be disjoint). I think I’d like to keep IDs being longs. This does mean that events need to have IDs again.
> - Objects themselves, represented as key-value dictionaries optionally implemented by an event-specific class.
>
> The DAO needs to support the following operations:
> 
> - Fetch the IDs for a particular object type.
> - Stream objects of a particular type
> - Look up objects by certain common keys (e.g. user ID, item ID)
> - Look up objects by arbitrary key (optional operation, can be optimized by the DAO if desired)
>
> The last operation can be used for supporting non-long IDs, by allowing items or users to be looked up by string or UUID or whatever.

**Comment by mdekstrand** [comment]
ping @kluver so he can track status on this ticket.
